### ISSUE TITLE
개발자 상세에서 다른 페이지 이동 경로 수정

### ISSUE THREAD

**Issue by eeseung** [prgrms-fe-devcourse/FEDC4_CUCUMIS_Pocojang#191]
- 개발자 상세 -> DM
- 개발자 상세 -> 프로필
이동 시 하위 경로가 userId가 아닌 개발자 포스트 id로 이동하는 문제가 있습니다.

**Comment by 1g2g** [comment]
앗 깜빡했네요..! 감사합니다🙇‍♀️
